# This is a basic example Blueprint for a Django web service and
# the PostgreSQL database it connects to.
databases:
  - name: tournament_note_staging_db
    plan: free
    region: singapore
    postgresMajorVersion: 15

services:
  - type: web
    name: tournament_note_staging
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec puma -C config/puma.rb"
    region: singapore
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tournament_note_staging_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default